services:
  ollama:
    restart: unless-stopped
    volumes:
      - /mnt/user/ai/ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    hostname: ollama
    network_mode: gf_network
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

networks:
  gf_network:
    external: true
