version: "3.8"
services:
  traefik-cloudflare-companion:
    container_name: traefik-cloudflare-companion
    environment:
      - TZ=Europe/Berlin
      - CF_TOKEN=your_cf_token
      - TARGET_DOMAIN=your_custom_domain.com
      - DOMAIN1=your_custom_domain.com
      - DOMAIN1_ZONE_ID=your_domain_zone_id
      - DOMAIN1_PROXIED=false
      - DRY_RUN=FALSE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: tiredofit/traefik-cloudflare-companion:latest
    network_mode: gf_network
    restart: unless-stopped
   traefik:
    image: traefik
    container_name: traefik
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=cloudflare_dns_api_token
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /mnt/user/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.services.api.loadbalancer.server.port: 8080
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      gf_network:
        ipv4_address: match_this_ip_with_a_router_forwarding_rule_on_443
    restart: unless-stopped
networks:
  gf_network:
    external: true
